version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge 

services:
  dockerapi:
    image: dotnetwithduh:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=blogdb;username=DuNetSeven;password=DuNetSeven"
    networks:
      - dockerapi-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "DuNetSeven"
      POSTGRES_PASSWORD: "DuNetSeven"
      POSTGRES_DB: "DuNetSeven"
    networks:
      - dockerapi-dev
volumes:
  db_volume:
         